# Generated by Django 4.0.4 on 2022-05-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
