# Generated by Django 4.0.4 on 2022-06-02 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0002_alter_subscribes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='subscription_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_to', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
