# Generated by Django 4.0.4 on 2022-06-02 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0003_alter_subscribes_subscription_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribes',
            name='subscribed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
