# Generated by Django 4.0.4 on 2022-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0005_alter_subscribes_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar/'),
        ),
        migrations.DeleteModel(
            name='subscribers',
        ),
    ]
