# Generated by Django 4.0.4 on 2022-06-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0006_alter_user_avatar_delete_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='Network_/static/avatar/'),
        ),
    ]
