# Generated by Django 3.2.6 on 2022-06-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0012_userposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='image',
            field=models.ImageField(upload_to='Network_/static/publication_image'),
        ),
    ]
