# Generated by Django 3.2.6 on 2022-06-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0013_alter_userposts_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPosts',
            new_name='Posts',
        ),
    ]
