# Generated by Django 4.0.4 on 2022-06-30 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0014_rename_userposts_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='avtor',
            new_name='author',
        ),
    ]
