# Generated by Django 4.0.4 on 2023-09-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0015_rename_avtor_posts_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_time', models.DateTimeField(auto_now=True)),
                ('save_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Network_.posts')),
                ('user_saved_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
