# Generated by Django 4.0.4 on 2023-09-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0017_rename_save_post_saved_post_save_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved_post',
            old_name='save_post_id',
            new_name='save_post',
        ),
    ]
