# Generated by Django 4.0.4 on 2023-09-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0019_alter_saved_post_save_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_post',
            name='save_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Network_.posts'),
        ),
    ]
