# Generated by Django 4.0.4 on 2023-09-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0020_alter_saved_post_save_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default="Hi i'm use a TarVin", max_length=120),
        ),
    ]
