# Generated by Django 4.0.4 on 2023-09-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0021_alter_user_avatar_alter_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='Network_/static/image/defaultavatar', null=True, upload_to='Network_/static/avatar'),
        ),
    ]
