# Generated by Django 4.2.5 on 2023-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0022_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='./static/image/default_avatar.png', null=True, upload_to='Network_/static/avatar'),
        ),
    ]
