# Generated by Django 4.2.5 on 2023-10-15 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0031_alter_posts_postvidorimg_alter_posts_priview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.AlterField(
            model_name='posts',
            name='PostVidOrImg',
            field=models.FileField(upload_to='static/PostData/<django.db.models.query_utils.DeferredAttribute object at 0x000001B74C362050>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='priview',
            field=models.ImageField(null=True, upload_to='static/PostData/<django.db.models.query_utils.DeferredAttribute object at 0x000001B74C362050>'),
        ),
    ]
