# Generated by Django 4.2.5 on 2023-10-15 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0032_remove_posts_image_alter_posts_postvidorimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='PostVidOrImg',
            field=models.FileField(upload_to='static/PostData/<django.db.models.query_utils.DeferredAttribute object at 0x0000018A9C9E3A10>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='priview',
            field=models.ImageField(null=True, upload_to='static/PostData/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
