# Generated by Django 4.2.5 on 2023-10-15 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0033_alter_posts_postvidorimg_alter_posts_priview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='PostVidOrImg',
            field=models.FileField(upload_to='static/PostData/<django.db.models.query_utils.DeferredAttribute object at 0x000001F50C922050>', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='posts',
            name='priview',
            field=models.ImageField(max_length=528, null=True, upload_to='static/PostData/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.DateTimeField>'),
        ),
    ]
