# Generated by Django 4.2.5 on 2023-10-16 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0034_alter_posts_postvidorimg_alter_posts_priview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='priview',
        ),
        migrations.AddField(
            model_name='posts',
            name='preview',
            field=models.ImageField(max_length=528, null=True, upload_to='Network_/static/PostData/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='PostVidOrImg',
            field=models.FileField(upload_to='Network_/static/PostData/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png', 'mp4'])]),
        ),
    ]
