# Generated by Django 4.2.5 on 2023-10-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network_', '0035_remove_posts_priview_posts_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='preview',
            field=models.ImageField(blank=True, default=1, max_length=528, upload_to='Network_/static/PostData/'),
            preserve_default=False,
        ),
    ]
