# Generated by Django 4.0.4 on 2022-06-28 08:40

import comments.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=comments.models.CustomDateTimeField(auto_now_add=True),
        ),
    ]
