# Generated by Django 3.2.6 on 2022-06-19 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Network_', '0014_rename_userposts_posts'),
        ('Like', '0003_alter_like_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Network_.posts'),
        ),
    ]
